### ISSUE TITLE
ultrapassagem sem ocupação da via adjacente

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/bike-reporter#3]
> Podes desde já acrescentar - ultrapassagem sem ocupação da via adjacente.

> Artigo 38.º — Realização da manobra
(…)
3 - Para a realização da manobra, o condutor deve ocupar o lado da faixa de rodagem destinado à circulação em sentido contrário ou, se existir mais que uma via de trânsito no mesmo sentido, a via de trânsito à esquerda daquela em que circula o veículo ultrapassado.
(…)
artigo 1.º do Código da Estrada:
u) «Via de trânsito» - zona longitudinal da faixa de rodagem destinada à circulação de uma única fila de veículos;

**Comment by mariojalves** [comment]
Estacionamento na ciclovia?

No Código da Estrada:

O Artigo 49 indica que «é proibido parar ou estacionar":

i) nas pistas de velocípedes, nos ilhéus direccionais, nas placas centrais das rotundas, nos passeios e demais locais destinados ao trânsito de peões
