### ISSUE TITLE
Missing link to play store

### ISSUE THREAD

**Issue by froque** [jfoclpf/bike-reporter#6]
https://play.google.com/store/apps/details?id=bike.reporter

**Comment by jfoclpf** [comment]
Olá, onde é que está a faltar o link exatamente?

**Comment by froque** [comment]
era no About, à semelhança do https://github.com/jfoclpf/form-for-parking-violation

também tinha procurado no README, mas escapou-me isto "A APP para Android está aqui."

**Comment by jfoclpf** [comment]
> era no About

bem visto, já corrigi, obrigado
